# values in this file will be appended to values of the same name in 
# prefecthq/prefect/netlify.toml

[[redirects]]
from = "/2*"
to = "/2*:splat"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/latest/:splat"
status = 301

[[redirects]]
from = "/latest/"
to = "/2.14.5/"
status = 200
