# values in this file will be appended to values of the same name in 
# prefecthq/prefect/netlify.toml

[[redirects]]
from = "https://docs.prefect.io/2*"
to = "https://docs.prefect.io/2*:splat"
status = 200
force = false

[[redirects]]
from = "https://docs.prefect.io/*"
to = "https://docs.prefect.io/latest/:splat"
status = 301
