# This workflow builds versioned copies of Prefect's documentation. 
# It is triggered automatically by two events in PrefectHQ/prefect:
#
# 1. A new release is published
# 2. A new commit is pushed to main branch's docs directory
#
# It also can be triggered manually by a user with write access to 
# the PrefectHQ/docs repository. In this case, the user must provide
# a version number as an input to the workflow.

name: Build Docs Version

permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types:
      - update_docs
  workflow_dispatch:
    inputs:
      version:
        description: 'The release tag to build and deploy (e.g., "2.8.0"). Use "latest" to build directly from the main branch of PrefectHQ/Prefect.'
        type: string
        required: true
        default: 'latest'
      display_name:
        description: 'The display name for the version (e.g., 2.8.0, 2.8.x, 2.7.x). Leave blank to use the version number.'
        type: string
        required: false
        default: ''

jobs:
  build_docs_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docs
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        path: ./docs
    
    - name: Set docs version
      run: |
        version="${{ github.event.client_payload.version }}"
        if [[ -z "$version" ]]; then
          version="${{ github.event.inputs.version }}"
        fi

        # if version is missing, exit with error
        if [[ -z "$version" ]]; then
          echo "Can't build versioned docs without a version!"
          exit 1
        fi

        # if the display name is blank, use the version number
        display_name="${{ github.event.client_payload.display_name }}"
        if [[ -z "$display_name" ]]; then
          display_name="${{ github.event.inputs.display_name }}"
        fi
        if [[ -z "$display_name" ]]; then
          display_name="$version"
        fi

        echo "version=$version" >> $GITHUB_ENV
        echo "display_name=$display_name" >> $GITHUB_ENV


    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x


    - name: Clone PrefectHQ/prefect
      run: |
        version="${{ env.version }}"
        if [[ $version == "latest" ]]; then
          git clone --depth 1 https://github.com/PrefectHQ/prefect.git prefect_source
        else
          git clone --branch "$version" --depth 1 https://github.com/PrefectHQ/prefect.git prefect_source
        fi

      working-directory: ${{ github.workspace }}/
      

    - name: Install Prefect and dependencies
      run: |
        pip install --upgrade pip 
        pip install --upgrade --upgrade-strategy eager  -e ".[dev]"

      working-directory: ${{ github.workspace }}/prefect_source


    - name: Install PrefectHQ/mkdocs-material-insiders
      env:
        MKDOCS_REPO_TEST_TOKEN: ${{ secrets.MKDOCS_REPO_TEST_TOKEN }}
      run: |
        pip install git+https://oauth2:$MKDOCS_REPO_TEST_TOKEN@github.com/PrefectHQ/mkdocs-material-insiders.git
        sudo apt-get install -y libcairo2
        

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
      
      working-directory: ${{ github.workspace }}/docs
    

    - name: Set branch name
      run: |
        version="${{ env.version }}"
        display_name="${{ env.display_name }}"
        timestamp="$(date +%s)"

        # create branch_display_name from display_name by replacing all
        # characters disallowed in git branch names with hyphens. 
        branch_display_name="$(echo "$display_name" | tr -c '[:alnum:]._' '-')"

        echo "branch_name=update-docs-$branch_display_name-$timestamp" >> $GITHUB_ENV
        echo "timestamp=$timestamp" >> $GITHUB_ENV


    - name: Update docs
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions-bot@example.com"

        version="${{ env.version }}"
        display_name="${{ env.display_name }}"
        branch_name="${{ env.branch_name }}"

        : # create the version branch, otherwise mike will create a branch
        : # that has non common history with main
        git checkout -b $branch_name
        git checkout main
        
        ln -s ../prefect_source/mkdocs.yml
        ln -s ../prefect_source/mkdocs.insiders.yml      
        ln -s ../prefect_source/src ./src
        ln -s ../prefect_source/docs ./docs

        # append the contents of ./overrides/templates/outdated.html to 
        # ./docs/overrides/main.html
        cat ./overrides/templates/outdated.html >> ./docs/overrides/main.html

        # if the version is anything other than 'latest', append the contents
        # of ./overrides/stylesheets/not-latest.css to ./docs/stylesheets/extra.css
        if [[ $version != "latest" ]]; then
          cat ./overrides/stylesheets/not-latest.css >> ./docs/stylesheets/extra.css
        fi

        # if there's a file named <version>.css in ./overrides/stylesheets, 
        # append it to ./docs/stylesheets/extra.css
        if [[ -f ./overrides/stylesheets/$version.css ]]; then
          cat ./overrides/stylesheets/$version.css >> ./docs/stylesheets/extra.css
        fi

        # add version string we can reference in Mkdocs templates
        sed -i "/extra:/a\    version_string: $display_name" ./mkdocs.yml

        # generate API docs
        prefect dev build-docs

        # build versioned docs
        mike deploy -F ./mkdocs.insiders.yml --update-aliases --branch $branch_name --prefix=versions "$display_name"
        
        rm -rf site
        unlink ./src
        unlink ./docs
        unlink ./mkdocs.yml
        unlink ./mkdocs.insiders.yml

      working-directory: ${{ github.workspace }}/docs


    - name: Update Netlify TOML
      env: 
        PREFECT_SOURCE: ${{ github.workspace }}/prefect_source
      run: |
        version="${{ env.version }}"
        # if version is not latest, skip this step
        if [[ $version != "latest" ]]; then
          exit 0
        fi

        git checkout $branch_name

        echo "Merging Netlify TOML overrides and additions..."
        python build-netlify-config.py \
          --input-config-path "$PREFECT_SOURCE/netlify.toml" \
          --overrides-path ./netlify.overrides.toml \
          --additions-path ./netlify.additions.toml \
          --output-config-path ./netlify_temp.toml
        

        # If $GITHUB_WORKSPACE/docs/netlify.toml is missing, 
        # or exist but differs from ./netlify_temp.toml, 
        # move ./netlify_temp.toml to $GITHUB_WORKSPACE/docs/netlify.toml.
        # otherwise, just remove ./netlify_temp.toml

        echo "Checking if Netlify TOML needs to be updated..."
        if [[ ! -f $GITHUB_WORKSPACE/docs/netlify.toml ]] || \
          [[ $(diff $GITHUB_WORKSPACE/docs/netlify.toml ./netlify_temp.toml) ]]; then
          echo "Updating Netlify TOML..."
          mv ./netlify_temp.toml $GITHUB_WORKSPACE/docs/netlify.toml
          
          # commit the change
          git add $GITHUB_WORKSPACE/docs/netlify.toml
          git commit -m "Update Netlify TOML for version $version"
        else
          rm ./netlify_temp.toml
        fi

      working-directory: ${{ github.workspace }}/docs/overrides/netlify


    - name: Sort docs versions
      run: |
        git checkout $branch_name
        python ./utilities/sort-docs-versions.py --versions-file-path ./versions/versions.json
        git add ./versions/versions.json
        git commit -m "Sort docs versions"

      working-directory: ${{ github.workspace }}/docs


    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version="${{ env.version }}"
        display_name="${{ env.display_name }}"
        branch_name="${{ env.branch_name }}"

        if [[ $display_name == "latest" ]]; then
          commit_title="Update latest documentation"
        else
          commit_title="Update documentation for $display_name"
        fi

        git push origin $branch_name
        gh pr create --base main --head $branch_name \
          --title "$commit_title" \
          --body "Automated documentation update for $display_name" \
          --label "documentation"
      
      working-directory: ${{ github.workspace }}/docs
